### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by Vanchen07** [Vanchen07/Pick-a-Table#2]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [ ] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [ ] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [ ] The site should look exactly like the actual site
- [ ] All relevant elements should have `cursor: pointer` on hover
- [ ] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [ ] Remove Redux logger and all console.log()'s from production

**Comment by jenkennedy** [comment]
- [ ] Update font and font sizes to match open table for navbar and dropdown items
- [ ] Fix error styling signup and login (errors themselves and buttons changing)
![screen shot 2019-03-04 at 3 02 26 pm](https://user-images.githubusercontent.com/39272166/53769002-68bd6980-3e8f-11e9-9024-5bd1257dc4c1.png)
